#pragma once

struct Emoji {
    const char* glyph;
    const char* name;
    const char* keywords;
    const char* aliases;
    bool skin_tone;
};

inline constexpr Emoji kEmojis[] = {
    {"😀", "grinning face", "smile happy", "cheerful cheery grin laugh nice smiling teeth", false},
    {"😃", "grinning face big eyes", "smile happy", "awesome grin mouth open smiling teeth yay", false},
    {"😄", "grinning squinting", "smile laugh", "eye eyes grin happy lol mouth open smiling", false},
    {"😁", "beaming face", "smile grin", "eye eyes grinning happy nice smiling teeth", false},
    {"😆", "grinning squinting closed", "laugh", "eyes haha hahaha happy lol mouth open rofl smile smiling", false},
    {"😅", "grinning sweat", "nervous laugh", "cold dejected excited mouth open smile smiling stress stressed", false},
    {"🤣", "rolling on floor", "rofl laugh", "crying funny haha happy hehe hilarious joy lmao lol roflmao tear laughing", false},
    {"😂", "face tears of joy", "cry laugh", "crying feels funny haha happy hehe hilarious lmao lol rofl roflmao tear", false},
    {"🙂", "slightly smiling", "smile", "happy", false},
    {"🙃", "upside down face", "silly", "hehe smile upside-down", false},
    {"😉", "winking face", "wink flirt", "heartbreaker sexy slide tease winks", false},
    {"😊", "smiling eyes", "blush happy", "eye glad satisfied smile", false},
    {"😇", "smiling halo", "angel innocent", "angelic angels blessed fairy fairytale fantasy happy peaceful smile spirit tale", false},
    {"🥰", "smiling hearts", "love adore", "crush heart ily romance smile you", false},
    {"😍", "heart eyes", "love crush", "143 bae eye feels heart-eyes hearts ily kisses romance romantic smile xoxo smiling", false},
    {"🤩", "star struck", "wow amazing", "excited eyes grinning smile star-struck starry-eyed", false},
    {"😘", "face blowing kiss", "kiss love", "adorbs bae flirt heart ily lover miss muah romantic smooch xoxo you", false},
    {"😗", "kissing face", "kiss", "143 date dating flirt ily love smooch smooches xoxo you", false},
    {"😚", "kissing closed eyes", "kiss", "143 bae blush date dating eye flirt ily kisses smooches xoxo", false},
    {"😙", "kissing smiling eyes", "kiss", "143 closed date dating eye flirt ily kisses love night smile", false},
    {"🥲", "smiling tear", "bittersweet", "glad grateful happy joy pain proud relieved smile smiley touched", false},
    {"😋", "face savoring", "yum tasty", "delicious eat food full hungry savor smile smiling um yummy", false},
    {"😛", "face tongue", "silly", "awesome cool nice party stuck-out sweet", false},
    {"😜", "winking tongue", "crazy silly", "epic eye funny joke loopy nutty party stuck-out wacky weirdo wink yolo", false},
    {"🤪", "zany face", "crazy wild", "eye eyes goofy large small", false},
    {"😝", "squinting tongue", "silly", "closed eye eyes gross horrible omg stuck-out taste whatever yolo", false},
    {"🤑", "money mouth", "rich greed", "money-mouth paid cash", false},
    {"🤗", "hugging face", "hug", "hands open smiling", false},
    {"🤭", "hand over mouth", "giggle secret", "giggling oops realization shock sudden surprise whoops", false},
    {"🤫", "shushing face", "quiet secret", "shh shush", false},
    {"🤔", "thinking face", "hmm think", "chin consider ponder pondering wondering", false},
    {"🤐", "zipper mouth", "silent secret", "keep quiet shut zip zipper-mouth", false},
    {"🤨", "raised eyebrow", "skeptical", "disapproval disbelief distrust emoji hmm mild skeptic skepticism surprise what", false},
    {"😐", "neutral face", "meh blank", "awkward deadpan expressionless fine jealous oh shade straight unamused unhappy unimpressed whatever", false},
    {"😑", "expressionless", "blank", "awkward dead fine inexpressive jealous meh not oh omg straight uh unhappy unimpressed whatever", false},
    {"😶", "face without mouth", "silent", "awkward blank expressionless mouthless mute quiet secret silence speechless", false},
    {"😏", "smirking face", "smirk flirt", "boss dapper homie kidding leer shade slick sly smug snicker suave suspicious swag sus", false},
    {"😒", "unamused", "bored annoyed", "... fine jealous jel jelly pissed smh ugh uhh unhappy weird whatever meh side eye", false},
    {"🙄", "rolling eyes", "annoyed sarcasm", "eyeroll shade ugh whatever", false},
    {"😬", "grimacing", "awkward", "awk dentist grimace grinning smile smiling", false},
    {"😮‍💨", "face exhaling", "sigh relief", "blow blowing exhale exhausted gasp groan smiley smoke whisper whistle", false},
    {"🤥", "lying face", "pinocchio lie", "liar", false},
    {"😌", "relieved face", "calm peace", "relief zen", false},
    {"😔", "pensive face", "sad thoughtful", "awful bored dejected died disappointed losing lost sucks", false},
    {"😪", "sleepy face", "tired sleep", "crying good night sad sleeping", false},
    {"🤤", "drooling face", "hungry want", "", false},
    {"😴", "sleeping face", "zzz sleep", "bed bedtime good goodnight nap night tired whatever yawn", false},
    {"😷", "face mask", "sick medical", "cold dentist dermatologist doctor dr germs medicine", false},
    {"🤒", "face thermometer", "sick fever", "ill", false},
    {"🤕", "face bandage", "hurt injured", "head-bandage injury ouch head", false},
    {"🤢", "nauseated face", "sick gross", "nasty vomit", false},
    {"🤮", "face vomiting", "sick throw up", "barf ew gross puke spew vomit", false},
    {"🤧", "sneezing face", "sick allergy", "fever flu gesundheit sneeze", false},
    {"🥵", "hot face", "heat sweating", "dying feverish panting red-faced stroke tongue", false},
    {"🥶", "cold face", "freezing", "blue blue-faced frostbite icicles subzero teeth", false},
    {"🥴", "woozy face", "drunk dizzy", "eyes intoxicated mouth tipsy uneven wavy", false},
    {"😵", "dizzy face", "confused spiral", "crossed-out dead eyes feels knocked out sick tired crossed", false},
    {"🤯", "exploding head", "mind blown", "explode mindblown no shocked way", false},
    {"🤠", "cowboy hat", "western", "cowgirl", false},
    {"🥳", "partying face", "celebrate party", "bday birthday celebration excited happy hat hooray horn", false},
    {"🥸", "disguised face", "glasses nose", "disguise eyebrow incognito moustache mustache person spy tache tash", false},
    {"😎", "smiling sunglasses", "cool", "awesome beach bright bro chilling rad relaxed shades slay smile style swag win", false},
    {"🤓", "nerd face", "geek glasses", "brainy clever expert gifted intelligent smart", false},
    {"🧐", "monocle face", "inspect curious", "classy fancy rich stuffy wealthy", false},
    {"😕", "confused face", "puzzled", "befuddled confusing dunno frown hm meh not sad sorry sure", false},
    {"😟", "worried face", "concern", "anxious butterflies nerves nervous sad stress stressed surprised worry", false},
    {"🙁", "slightly frowning", "sad", "frown", false},
    {"☹️", "frowning face", "sad unhappy", "frown", false},
    {"😮", "open mouth", "surprised wow", "believe forgot omg shocked sympathy unbelievable unreal whoa you", false},
    {"😯", "hushed face", "surprised", "epic omg stunned whoa woah", false},
    {"😲", "astonished face", "shocked amazed", "cost no omg totally way", false},
    {"😳", "flushed face", "embarrassed blush", "amazed awkward crazy dazed dead disbelief geez heat hot impressed jeez what wow", false},
    {"🥺", "pleading face", "puppy eyes please", "begging big mercy not pretty sad why", false},
    {"😦", "frowning open mouth", "shocked", "caught frown guard scared scary surprise what wow", false},
    {"😧", "anguished face", "pain shock", "forgot scared scary stressed surprise unhappy what wow", false},
    {"😨", "fearful face", "scared afraid", "anxious blame fear worried", false},
    {"😰", "anxious sweat", "nervous worried", "blue cold eek mouth open rushed scared yikes", false},
    {"😥", "sad relieved sweat", "disappointed", "anxious call close complicated not time whew but", false},
    {"😢", "crying face", "sad tear", "awful cry feels miss triste unhappy", false},
    {"😭", "loudly crying", "sob sad", "bawling cry tear tears unhappy", false},
    {"😱", "screaming fear", "horror shocked", "epic fearful munch scared scream screamer surprised woah", false},
    {"😖", "confounded face", "frustrated", "annoyed confused cringe distraught feels mad sad", false},
    {"😣", "persevering face", "struggle", "concentrate concentration focus headache persevere", false},
    {"😞", "disappointed face", "sad fail", "awful blame dejected losing unhappy", false},
    {"😓", "downcast sweat", "tired sad", "close cold feels headache nervous scared yikes", false},
    {"😩", "weary face", "tired exhausted", "crying fail feels hungry mad nooo sad sleepy unhappy", false},
    {"😫", "tired face", "exhausted", "cost feels nap sad sneeze", false},
    {"🥱", "yawning face", "bored tired", "bedtime goodnight nap night sleep sleepy whatever yawn zzz", false},
    {"😤", "steam nose", "angry proud", "anger feels fume fuming furious fury mad triumph unhappy won from", false},
    {"😡", "pouting face", "angry mad", "anger enraged feels maddening rage red shade unhappy upset", false},
    {"😠", "angry face", "mad annoyed", "anger blame feels frustrated maddening rage shade unhappy upset", false},
    {"🤬", "cursing face", "swear angry", "censor cussing mad mouth pissed swearing symbols", false},
    {"😈", "smiling horns", "devil evil", "demon fairy fairytale fantasy purple shade smile tale hell satan", false},
    {"👿", "angry horns", "devil imp", "demon evil fairy fairytale fantasy mischievous purple shade tale satan", false},
    {"💀", "skull", "dead danger", "body death fairy fairytale i’m lmao monster tale yolo die skeleton", false},
    {"☠️", "skull crossbones", "danger poison", "bone dead death monster", false},
    {"💩", "pile of poo", "poop funny", "bs comic doo dung fml monster smelly smh stink stinks stinky turd shit crap hankey dookie dump", false},
    {"🤡", "clown face", "circus funny", "joker fool", false},
    {"👹", "ogre", "monster japanese", "creature devil fairy fairytale fantasy mask scary tale", false},
    {"👺", "goblin", "monster japanese", "angry creature fairy fairytale fantasy mask mean tale", false},
    {"👻", "ghost", "halloween spooky", "boo creature excited fairy fairytale fantasy haunting monster scary silly tale spook", false},
    {"👽", "alien", "ufo space", "creature extraterrestrial fairy fairytale fantasy monster tale", false},
    {"👾", "alien monster", "space game", "creature extraterrestrial fairy fairytale fantasy gamer games pixelated tale ufo", false},
    {"🤖", "robot", "bot ai", "monster", false},
    {"👋", "waving hand", "hello bye", "cya g2g greetings gtg hey hi later outtie ttfn ttyl wave yo you", true},
    {"🤚", "raised back hand", "stop", "backhand", true},
    {"🖐️", "hand splayed", "five high five", "finger fingers raised stop", true},
    {"✋", "raised hand", "stop high five", "", true},
    {"🖖", "vulcan salute", "spock star trek", "finger hand hands", true},
    {"👌", "ok hand", "okay perfect", "awesome bet dope fleek fosho got gotcha legit pinch rad sure sweet three", true},
    {"🤌", "pinched fingers", "italian gesture", "hand hold huh interrogation patience relax sarcastic ugh what zip", true},
    {"🤏", "pinching hand", "small tiny", "amount bit fingers little sort", true},
    {"✌️", "victory hand", "peace two", "", true},
    {"🤞", "crossed fingers", "luck hope", "cross finger hand", true},
    {"🤟", "love you gesture", "ily sign", "fingers hand love-you three", true},
    {"🤘", "sign horns", "rock metal", "finger hand rock-on", true},
    {"🤙", "call me hand", "shaka hang loose", "", true},
    {"👈", "backhand index left", "point", "finger hand pointing", true},
    {"👉", "backhand index right", "point", "finger hand pointing", true},
    {"👆", "backhand index up", "point up", "finger hand pointing", true},
    {"🖕", "middle finger", "rude", "hand fuck fu flip off bird", true},
    {"👇", "backhand index down", "point down", "finger hand pointing", true},
    {"☝️", "index up", "one point", "finger hand pointing this", true},
    {"👍", "thumbs up", "yes good approve", "+1 hand like thumb", true},
    {"👎", "thumbs down", "no bad disapprove", "-1 dislike good hand nope thumb", true},
    {"✊", "raised fist", "power protest", "clenched hand punch solidarity", true},
    {"👊", "oncoming fist", "punch bump", "absolutely agree boom bro bruh clenched correct hand knuckle pound rock ttyl", true},
    {"🤛", "left fist", "bump", "left-facing leftwards facing", true},
    {"🤜", "right fist", "bump", "right-facing rightwards facing", true},
    {"👏", "clapping hands", "applause bravo", "approval awesome clap congrats congratulations excited good great hand homie job nice prayed well yay", true},
    {"🙌", "raising hands", "celebrate hooray", "celebration gesture hand praise raised", true},
    {"👐", "open hands", "jazz hands", "hand hug swerve", true},
    {"🤲", "palms up", "pray offer", "cupped dua hands prayer together wish", true},
    {"🤝", "handshake", "deal agree", "agreement hand meeting shake", true},
    {"🙏", "folded hands", "please pray thanks", "appreciate ask beg blessed bow cmon five gesture hand high thx", true},
    {"✍️", "writing hand", "write sign", "", true},
    {"💅", "nail polish", "manicure fancy", "bored care cosmetics done makeup whatever", true},
    {"🤳", "selfie", "phone camera", "", true},
    {"💪", "flexed biceps", "strong muscle gym", "arm beast bench bodybuilder bro curls flex gains jacked press ripped weightlift", true},
    {"🦾", "mechanical arm", "prosthetic robot", "accessibility", false},
    {"🦿", "mechanical leg", "prosthetic", "accessibility", false},
    {"🦵", "leg", "limb kick", "bent foot knee", true},
    {"🦶", "foot", "stomp kick", "ankle feet", true},
    {"👂", "ear", "listen hear", "body ears hearing listening sound", true},
    {"🦻", "ear hearing aid", "deaf", "accessibility hard", true},
    {"👃", "nose", "smell sniff", "body noses nosey odor smells", true},
    {"🧠", "brain", "smart think", "intelligent", false},
    {"🫀", "anatomical heart", "organ", "beat cardiology heartbeat pulse real red", false},
    {"🫁", "lungs", "breathe organ", "breath exhalation inhalation lung respiration", false},
    {"🦷", "tooth", "dental dentist", "pearly teeth white", false},
    {"🦴", "bone", "skeleton dog", "bones wishbone", false},
    {"👀", "eyes", "look see watch", "body eye googly looking omg peep seeing", false},
    {"👁️", "eye", "see look", "body one", false},
    {"👅", "tongue", "taste lick", "body slurp", false},
    {"👄", "mouth", "lips kiss", "beauty body kissing lipstick", false},
    {"👶", "baby", "child infant", "babies children goo newborn pregnant young", true},
    {"🧒", "child", "kid young", "bright-eyed grandchild younger", true},
    {"👦", "boy", "child male", "bright-eyed grandson kid son young younger", true},
    {"👧", "girl", "child female", "bright-eyed daughter granddaughter kid virgo young younger zodiac", true},
    {"🧑", "person", "adult human", "", true},
    {"👱", "person blond hair", "blonde", "blond-haired human person:", true},
    {"👨", "man", "male adult", "bro", true},
    {"👩", "woman", "female adult", "lady", true},
    {"🧓", "older person", "elderly senior", "adult grandparent old wise", true},
    {"👴", "old man", "grandpa elderly", "adult bald gramps grandfather wise", true},
    {"👵", "old woman", "grandma elderly", "adult grandmother granny lady wise", true},
    {"🐶", "dog face", "puppy pet", "adorbs animal puppies", false},
    {"🐱", "cat face", "kitten pet", "animal kitty", false},
    {"🐭", "mouse face", "rodent", "animal", false},
    {"🐹", "hamster", "pet rodent", "animal", false},
    {"🐰", "rabbit face", "bunny easter", "animal pet", false},
    {"🦊", "fox", "animal wild", "", false},
    {"🐻", "bear", "animal wild", "grizzly growl honey", false},
    {"🐼", "panda", "animal china", "bamboo", false},
    {"🐨", "koala", "animal australia", "bear down marsupial under", false},
    {"🐯", "tiger face", "wild cat", "animal big predator", false},
    {"🦁", "lion", "king wild", "alpha animal leo mane order rawr roar safari strong zodiac", false},
    {"🐮", "cow face", "farm moo", "animal milk", false},
    {"🐷", "pig face", "farm oink", "animal bacon pork", false},
    {"🐸", "frog", "amphibian", "animal", false},
    {"🐵", "monkey face", "primate", "animal banana", false},
    {"🙈", "see no evil", "monkey", "embarrassed forbidden forgot gesture hide omg prohibited scared secret smh watch", false},
    {"🙉", "hear no evil", "monkey", "animal ears forbidden gesture listen not prohibited secret shh tmi", false},
    {"🙊", "speak no evil", "monkey", "animal forbidden gesture not oops prohibited quiet secret stealth", false},
    {"🐔", "chicken", "bird farm", "animal ornithology", false},
    {"🐧", "penguin", "bird cold", "animal antarctica ornithology", false},
    {"🐦", "bird", "fly tweet", "animal ornithology", false},
    {"🐤", "baby chick", "bird yellow", "animal ornithology", false},
    {"🦆", "duck", "bird water", "animal ornithology", false},
    {"🦅", "eagle", "bird america", "animal ornithology", false},
    {"🦉", "owl", "bird night wise", "animal ornithology", false},
    {"🐝", "honeybee", "insect buzz", "animal bee bumblebee honey nature spring", false},
    {"🪲", "beetle", "insect bug", "animal", false},
    {"🐛", "bug", "insect caterpillar", "animal garden", false},
    {"🦋", "butterfly", "insect pretty", "", false},
    {"🐌", "snail", "slow shell", "animal escargot garden nature slug", false},
    {"🐙", "octopus", "sea ocean", "animal creature", false},
    {"🦑", "squid", "sea ocean", "animal food mollusk", false},
    {"🦐", "shrimp", "seafood ocean", "food shellfish small", false},
    {"🐠", "tropical fish", "ocean sea", "animal fishes", false},
    {"🐟", "fish", "ocean sea", "animal dinner fishes fishing pisces zodiac", false},
    {"🐬", "dolphin", "ocean smart", "animal beach flipper", false},
    {"🐳", "spouting whale", "ocean big", "animal beach", false},
    {"🦈", "shark", "ocean danger", "animal fish", false},
    {"🐊", "crocodile", "reptile danger", "animal zoo", false},
    {"🐢", "turtle", "slow reptile", "animal terrapin tortoise", false},
    {"🦎", "lizard", "reptile", "animal", false},
    {"🐍", "snake", "reptile danger", "animal bearer ophiuchus serpent zodiac", false},
    {"🦕", "sauropod", "dinosaur dino", "brachiosaurus brontosaurus diplodocus", false},
    {"🦖", "t-rex", "dinosaur dino", "rex tyrannosaurus", false},
    {"🐘", "elephant", "big animal", "", false},
    {"🦏", "rhinoceros", "animal horn", "", false},
    {"🦛", "hippopotamus", "animal water", "hippo", false},
    {"🐪", "camel", "desert hump", "animal dromedary one", false},
    {"🦒", "giraffe", "tall animal", "spots", false},
    {"🦘", "kangaroo", "australia jump", "animal joey marsupial", false},
    {"🐎", "horse", "ride gallop", "animal equestrian farm racehorse racing", false},
    {"🦄", "unicorn", "fantasy magic", "", false},
    {"🍎", "red apple", "fruit healthy", "diet food health ripe", false},
    {"🍊", "tangerine", "fruit orange", "citrus nectarine vitamin", false},
    {"🍋", "lemon", "fruit sour citrus", "", false},
    {"🍌", "banana", "fruit yellow", "potassium", false},
    {"🍉", "watermelon", "fruit summer", "", false},
    {"🍇", "grapes", "fruit wine", "dionysus grape", false},
    {"🍓", "strawberry", "fruit berry", "", false},
    {"🫐", "blueberries", "fruit berry", "berries bilberry blue blueberry food", false},
    {"🍒", "cherries", "fruit red", "berries cherry", false},
    {"🍑", "peach", "fruit butt", "ass booty", false},
    {"🥭", "mango", "fruit tropical", "food", false},
    {"🍍", "pineapple", "fruit tropical", "colada pina", false},
    {"🥥", "coconut", "tropical nut", "colada palm piña", false},
    {"🥝", "kiwi fruit", "green fruit", "food", false},
    {"🍅", "tomato", "vegetable fruit", "food", false},
    {"🍆", "eggplant", "vegetable purple", "aubergine dick", false},
    {"🥑", "avocado", "healthy green", "food fruit", false},
    {"🥦", "broccoli", "vegetable healthy", "cabbage wild", false},
    {"🥬", "leafy green", "salad vegetable", "bok burgers cabbage choy kale lettuce", false},
    {"🥒", "cucumber", "vegetable green", "food pickle", false},
    {"🌶️", "hot pepper", "spicy chili", "", false},
    {"🫑", "bell pepper", "vegetable", "capsicum food", false},
    {"🌽", "ear of corn", "vegetable farm", "crops maize maze", false},
    {"🥕", "carrot", "vegetable orange", "food", false},
    {"🧄", "garlic", "cooking spice", "flavoring", false},
    {"🧅", "onion", "cooking vegetable", "flavoring", false},
    {"🥔", "potato", "vegetable starch", "food", false},
    {"🍞", "bread", "bakery toast", "carbs food grain loaf restaurant wheat", false},
    {"🥐", "croissant", "french bakery", "bread breakfast crescent food roll", false},
    {"🥖", "baguette", "french bread", "food", false},
    {"🧀", "cheese wedge", "dairy food", "", false},
    {"🥚", "egg", "breakfast protein", "food", false},
    {"🍳", "cooking", "fried egg breakfast", "easy fry frying over pan restaurant side sunny up", false},
    {"🥓", "bacon", "breakfast meat", "food", false},
    {"🥩", "cut of meat", "steak beef", "chop lambchop porkchop red", false},
    {"🍗", "poultry leg", "chicken drumstick", "bone hungry turkey", false},
    {"🍖", "meat on bone", "bbq food", "", false},
    {"🌭", "hot dog", "food sausage", "frankfurter hotdog", false},
    {"🍔", "hamburger", "burger fast food", "eat hungry", false},
    {"🍟", "french fries", "fast food", "", false},
    {"🍕", "pizza", "italian food cheese", "hungry pepperoni slice", false},
    {"🌮", "taco", "mexican food", "", false},
    {"🌯", "burrito", "mexican wrap food", "", false},
    {"🥗", "green salad", "healthy food", "", false},
    {"🍝", "spaghetti", "italian pasta food", "meatballs restaurant", false},
    {"🍜", "steaming bowl", "ramen noodles soup", "chopsticks food noodle pho", false},
    {"🍲", "pot of food", "stew soup", "", false},
    {"🍛", "curry rice", "indian food", "", false},
    {"🍣", "sushi", "japanese food fish", "", false},
    {"🍱", "bento box", "japanese lunch", "food", false},
    {"🍤", "fried shrimp", "seafood tempura", "prawn", false},
    {"🍙", "rice ball", "japanese onigiri", "food", false},
    {"🍚", "cooked rice", "asian food", "", false},
    {"🍘", "rice cracker", "japanese snack", "food", false},
    {"🍧", "shaved ice", "dessert cold", "restaurant sweet", false},
    {"🍨", "ice cream", "dessert cold sweet", "food restaurant", false},
    {"🍦", "soft ice cream", "dessert cone", "food icecream restaurant serve sweet", false},
    {"🍰", "shortcake", "cake dessert birthday", "pastry slice sweet", false},
    {"🎂", "birthday cake", "party celebration", "bday dessert happy pastry sweet", false},
    {"🧁", "cupcake", "dessert sweet", "bakery sprinkles sugar treat", false},
    {"🍪", "cookie", "dessert sweet snack", "chip chocolate", false},
    {"🍫", "chocolate bar", "candy sweet", "dessert halloween tooth", false},
    {"🍬", "candy", "sweet treat", "cavities dessert halloween restaurant tooth wrapper", false},
    {"🍭", "lollipop", "candy sweet", "dessert food restaurant", false},
    {"🍩", "doughnut", "donut sweet breakfast", "dessert food", false},
    {"☕", "hot beverage", "coffee tea morning", "cafe caffeine chai drink steaming", false},
    {"🍵", "teacup", "tea green japanese", "beverage cup drink handle oolong without", false},
    {"🧃", "beverage box", "juice drink", "straw sweet", false},
    {"🥤", "cup with straw", "soda drink", "juice malt soft water", false},
    {"🧋", "bubble tea", "boba drink", "food milk pearl", false},
    {"🍺", "beer mug", "drink alcohol pub", "ale bar booze drinking drinks octoberfest oktoberfest pint stein summer brew drunk", false},
    {"🍻", "clinking beers", "cheers drink", "alcohol bar beer booze bottoms clink drinking drinks mugs drunk", false},
    {"🥂", "clinking glasses", "toast champagne celebrate", "clink drink glass", false},
    {"🍷", "wine glass", "drink alcohol red", "bar beverage booze club drinking drinks restaurant vino drunk", false},
    {"🥃", "tumbler glass", "whiskey drink", "liquor scotch shot whisky", false},
    {"🍸", "cocktail glass", "martini drink", "alcohol bar booze club drinking drinks mad men", false},
    {"🍹", "tropical drink", "cocktail vacation", "alcohol bar booze club drinking drinks drunk mai party tai tropics", false},
    {"🧉", "mate", "drink argentina", "", false},
    {"⚽", "soccer ball", "football sport", "futbol", false},
    {"🏀", "basketball", "sport ball", "hoop", false},
    {"🏈", "american football", "sport nfl", "ball bowl super", false},
    {"⚾", "baseball", "sport ball", "", false},
    {"🎾", "tennis", "sport racket", "ball racquet", false},
    {"🏐", "volleyball", "sport beach", "ball game", false},
    {"🏉", "rugby football", "sport", "ball", false},
    {"🎱", "pool 8 ball", "billiards game", "8ball billiard eight", false},
    {"🏓", "ping pong", "table tennis sport", "ball bat game paddle pingpong", false},
    {"🏸", "badminton", "sport racket", "birdie game racquet shuttlecock", false},
    {"🥅", "goal net", "soccer hockey", "", false},
    {"🏒", "ice hockey", "sport stick", "game puck", false},
    {"⛳", "flag in hole", "golf sport", "", false},
    {"🏹", "bow and arrow", "archery sport", "archer sagittarius tool weapon zodiac", false},
    {"🎣", "fishing pole", "fish hobby", "entertainment sport", false},
    {"🥊", "boxing glove", "fight sport", "", false},
    {"🥋", "martial arts uniform", "karate judo", "taekwondo", false},
    {"🎿", "skis", "winter sport snow", "ski", false},
    {"⛷️", "skier", "winter snow sport", "ski", false},
    {"🏂", "snowboarder", "winter sport", "ski snow snowboard", false},
    {"🎯", "direct hit", "dart target bullseye", "bull entertainment game", false},
    {"🎮", "video game", "gaming controller", "entertainment", false},
    {"🕹️", "joystick", "gaming arcade retro", "game video videogame", false},
    {"🎲", "game die", "dice board game", "entertainment", false},
    {"🧩", "puzzle piece", "jigsaw game", "clue interlocking", false},
    {"♟️", "chess pawn", "board game strategy", "dupe expendable", false},
    {"🎭", "performing arts", "theater drama mask", "actor actress art entertainment theatre thespian", false},
    {"🎨", "artist palette", "art paint creative", "artsy arty colorful entertainment museum painter painting", false},
    {"🎬", "clapper board", "movie film cinema", "action", false},
    {"🎤", "microphone", "sing karaoke music", "mic sound", false},
    {"🎧", "headphone", "music listen audio", "earbud sound", false},
    {"🎼", "musical score", "music sheet notes", "note", false},
    {"🎹", "musical keyboard", "piano music", "instrument", false},
    {"🥁", "drum", "music beat", "drumsticks", false},
    {"🎷", "saxophone", "music jazz instrument", "sax", false},
    {"🎺", "trumpet", "music brass instrument", "", false},
    {"🎸", "guitar", "music rock instrument", "strat", false},
    {"🪕", "banjo", "music country instrument", "stringed", false},
    {"🎻", "violin", "music classical instrument", "", false},
    {"🎉", "party popper", "celebrate confetti", "awesome birthday celebration excited hooray tada woohoo", false},
    {"🎊", "confetti ball", "celebrate party", "celebration woohoo", false},
    {"🎈", "balloon", "party birthday", "celebrate celebration", false},
    {"🎁", "wrapped gift", "present birthday christmas", "bow box celebration surprise", false},
    {"🎀", "ribbon", "gift bow decoration", "celebration", false},
    {"🎄", "christmas tree", "holiday xmas", "celebration", false},
    {"🎃", "jack o lantern", "halloween pumpkin", "celebration jack-o-lantern", false},
    {"🎆", "fireworks", "celebrate new year", "boom celebration entertainment yolo", false},
    {"🎇", "sparkler", "celebrate fireworks", "boom celebration sparkle", false},
    {"🚗", "automobile", "car drive vehicle", "driving", false},
    {"🚕", "taxi", "car ride cab", "cabbie drive vehicle yellow", false},
    {"🚙", "sport utility vehicle", "suv car", "drive recreational sportutility", false},
    {"🚌", "bus", "public transport", "school vehicle", false},
    {"🚎", "trolleybus", "bus transport", "tram trolley", false},
    {"🏎️", "racing car", "fast f1 speed", "zoom", false},
    {"🚓", "police car", "cop law emergency", "5–0 cops patrol", false},
    {"🚑", "ambulance", "medical emergency", "vehicle", false},
    {"🚒", "fire engine", "firefighter emergency", "truck", false},
    {"🚐", "minibus", "van transport", "bus drive vehicle", false},
    {"🛻", "pickup truck", "vehicle truck", "automobile car flatbed pick-up transportation", false},
    {"🚚", "delivery truck", "shipping transport", "car drive vehicle", false},
    {"🚛", "articulated lorry", "truck shipping", "car drive move semi vehicle", false},
    {"🚜", "tractor", "farm vehicle", "", false},
    {"🏍️", "motorcycle", "bike ride", "racing", false},
    {"🛵", "motor scooter", "vespa ride", "", false},
    {"🚲", "bicycle", "bike cycle ride", "class cycling cyclist gang spin spinning", false},
    {"🛴", "kick scooter", "ride transport", "", false},
    {"✈️", "airplane", "flight travel fly", "aeroplane flying jet plane", false},
    {"🛫", "airplane departure", "flight takeoff travel", "aeroplane check-in departures plane", false},
    {"🛬", "airplane arrival", "flight landing travel", "aeroplane arrivals arriving plane", false},
    {"🚀", "rocket", "space launch nasa", "rockets travel", false},
    {"🛸", "flying saucer", "ufo alien space", "aliens extra terrestrial", false},
    {"🚁", "helicopter", "fly transport", "copter roflcopter travel vehicle", false},
    {"⛵", "sailboat", "boat sail ocean", "resort sailing sea yacht", false},
    {"🚤", "speedboat", "boat fast water", "billionaire lake luxury millionaire summer travel", false},
    {"🛳️", "passenger ship", "cruise boat ocean", "", false},
    {"⛴️", "ferry", "boat transport", "passenger", false},
    {"🚢", "ship", "boat ocean cargo", "passenger travel", false},
    {"⚓", "anchor", "ship navy maritime", "tool", false},
    {"🏠", "house", "home building", "country heart ranch settle simple suburban suburbia where", false},
    {"🏡", "house garden", "home suburban", "building country heart ranch settle simple suburbia where", false},
    {"🏢", "office building", "work city corporate", "cubical job", false},
    {"🏬", "department store", "shopping mall", "building", false},
    {"🏭", "factory", "industry manufacturing", "building", false},
    {"🏗️", "building construction", "crane work", "", false},
    {"🗼", "tokyo tower", "landmark japan", "", false},
    {"🗽", "statue of liberty", "america new york", "ny nyc", false},
    {"⛪", "church", "religion christian", "bless chapel cross", false},
    {"🕌", "mosque", "religion islam", "masjid muslim", false},
    {"🛕", "hindu temple", "religion india", "", false},
    {"🕍", "synagogue", "religion jewish", "jew judaism temple", false},
    {"⛩️", "shinto shrine", "japan religion", "", false},
    {"🌋", "volcano", "eruption mountain", "nature", false},
    {"🏔️", "snow capped mountain", "nature alpine", "cold snow-capped", false},
    {"⛰️", "mountain", "nature hike", "", false},
    {"🏕️", "camping", "tent outdoor nature", "", false},
    {"🏖️", "beach umbrella", "vacation summer", "", false},
    {"🏜️", "desert", "sand dry hot", "", false},
    {"🏝️", "desert island", "tropical vacation palm", "", false},
    {"🌅", "sunrise", "morning sky beautiful", "nature sun", false},
    {"🌄", "sunrise mountains", "morning nature", "over sun", false},
    {"🌠", "shooting star", "wish night sky", "falling space", false},
    {"🌌", "milky way", "galaxy space stars", "", false},
    {"🌃", "night stars", "city night sky", "star", false},
    {"🌆", "cityscape dusk", "sunset city", "building evening landscape sun", false},
    {"🌇", "sunset", "evening city sky", "building dusk sun", false},
    {"🌉", "bridge at night", "city landmark", "", false},
    {"⌚", "watch", "time wrist", "clock", false},
    {"📱", "mobile phone", "cell smartphone", "communication telephone", false},
    {"💻", "laptop", "computer work tech", "office pc personal", false},
    {"⌨️", "keyboard", "type computer input", "", false},
    {"🖥️", "desktop computer", "monitor screen pc", "", false},
    {"🖨️", "printer", "office paper", "computer", false},
    {"🖱️", "computer mouse", "click input tech", "", false},
    {"💾", "floppy disk", "save retro storage", "computer", false},
    {"💿", "optical disk", "cd dvd storage", "blu-ray computer", false},
    {"📀", "dvd", "disk movie storage", "blu-ray cd computer optical", false},
    {"📷", "camera", "photo picture", "selfie snap tbt trip video", false},
    {"📸", "camera flash", "photo snapshot", "video", false},
    {"📹", "video camera", "film record movie", "camcorder tbt", false},
    {"🎥", "movie camera", "film cinema", "bollywood hollywood record", false},
    {"📞", "telephone receiver", "phone call", "communication voip", false},
    {"☎️", "telephone", "phone call old", "", false},
    {"📟", "pager", "beeper retro", "communication", false},
    {"📠", "fax machine", "office document", "communication", false},
    {"📺", "television", "tv watch screen", "video", false},
    {"📻", "radio", "music broadcast audio", "entertainment tbt video", false},
    {"⏰", "alarm clock", "wake time morning", "hours hrs late waiting", false},
    {"⌛", "hourglass done", "time wait done", "sand timer", false},
    {"⏳", "hourglass not done", "time wait loading", "flowing hours sand timer waiting yolo", false},
    {"📡", "satellite antenna", "signal broadcast", "aliens contact dish science", false},
    {"🔋", "battery", "power charge energy", "", false},
    {"🔌", "electric plug", "power charge outlet", "electricity", false},
    {"💡", "light bulb", "idea bright lamp", "comic electric", false},
    {"🔦", "flashlight", "torch light dark", "electric tool", false},
    {"🕯️", "candle", "light flame wax", "", false},
    {"🧯", "fire extinguisher", "safety emergency", "extinguish quench", false},
    {"🛢️", "oil drum", "fuel barrel", "", false},
    {"💸", "money wings", "spend cash flying", "bank banknote bill billion dollar fly million note pay", false},
    {"💵", "dollar banknote", "money cash usd", "bank bill currency note", false},
    {"💴", "yen banknote", "money japan jpy", "bank bill currency note", false},
    {"💶", "euro banknote", "money europe eur", "100 bank bill currency note rich", false},
    {"💷", "pound banknote", "money uk gbp", "bank bill billion cash currency note pounds", false},
    {"💰", "money bag", "rich wealth dollars", "bank bet billion cash cost dollar gold million moneybag paid paying pot win", false},
    {"💳", "credit card", "payment bank", "cash charge money pay", false},
    {"💎", "gem stone", "diamond jewel rich", "engagement money romance wedding", false},
    {"⚖️", "balance scale", "justice law weight", "libra scales tool zodiac", false},
    {"🔧", "wrench", "tool fix repair", "home improvement spanner", false},
    {"🔨", "hammer", "tool build construction", "home improvement repairs", false},
    {"⚒️", "hammer pick", "tool mining", "", false},
    {"🛠️", "hammer wrench", "tools repair fix", "spanner tool", false},
    {"⛏️", "pick", "tool mining dig", "hammer", false},
    {"🔩", "nut bolt", "hardware screw", "home improvement tool", false},
    {"⚙️", "gear", "settings mechanical cog", "cogwheel tool", false},
    {"🔗", "link", "chain url connect", "links", false},
    {"⛓️", "chains", "link metal lock", "chain", false},
    {"🔫", "water pistol", "gun toy squirt", "handgun revolver tool weapon", false},
    {"💣", "bomb", "explosive danger", "boom comic dangerous explosion hot", false},
    {"🧨", "firecracker", "explosive celebrate", "dynamite fire fireworks light pop popping spark", false},
    {"🔪", "kitchen knife", "cut cook chef", "cooking hocho tool weapon", false},
    {"🗡️", "dagger", "sword weapon knife", "", false},
    {"⚔️", "crossed swords", "fight battle weapon", "", false},
    {"🛡️", "shield", "protect defense armor", "weapon", false},
    {"🚬", "cigarette", "smoke tobacco", "smoking", false},
    {"⚰️", "coffin", "death funeral", "dead vampire", false},
    {"⚱️", "funeral urn", "death ashes", "", false},
    {"🏺", "amphora", "vase ancient pottery", "aquarius cooking drink jug tool weapon zodiac", false},
    {"🔮", "crystal ball", "fortune magic future", "fairy fairytale fantasy tale tool", false},
    {"📿", "prayer beads", "religion meditation", "clothing necklace", false},
    {"🧿", "nazar amulet", "evil eye protection", "bead blue charm evil-eye talisman", false},
    {"💈", "barber pole", "haircut salon", "cut fresh shave", false},
    {"⚗️", "alembic", "chemistry science lab", "tool", false},
    {"🔭", "telescope", "space stars science", "contact extraterrestrial tool", false},
    {"🔬", "microscope", "science lab research", "experiment tool", false},
    {"🕳️", "hole", "empty void", "", false},
    {"🩹", "adhesive bandage", "bandaid hurt fix", "", false},
    {"🩺", "stethoscope", "doctor medical health", "heart medicine", false},
    {"💊", "pill", "medicine drug pharmacy", "doctor drugs medicated pills sick vitamin", false},
    {"💉", "syringe", "vaccine medical shot", "doctor flu medicine needle sick tool vaccination", false},
    {"🩸", "drop of blood", "medical donate", "bleed donation injury medicine menstruation", false},
    {"🧬", "dna", "genetics science biology", "biologist evolution gene life", false},
    {"🦠", "microbe", "virus bacteria germ", "amoeba science", false},
    {"🧫", "petri dish", "science lab bacteria", "biologist biology culture", false},
    {"🧪", "test tube", "science chemistry lab", "chemist experiment", false},
    {"🌡️", "thermometer", "temperature hot cold", "weather", false},
    {"🧹", "broom", "clean sweep witch", "cleaning sweeping", false},
    {"🧺", "basket", "laundry picnic", "farming", false},
    {"🧻", "roll of paper", "toilet tissue bathroom", "towels tp", false},
    {"🚽", "toilet", "bathroom wc", "loo restroom pee", false},
    {"🚿", "shower", "bathroom water clean", "", false},
    {"🛁", "bathtub", "bath relax water", "", false},
    {"🧼", "soap", "clean wash hygiene", "bar bathing cleaning lather soapdish", false},
    {"🪥", "toothbrush", "dental hygiene clean", "bathroom brush teeth toiletry", false},
    {"🪒", "razor", "shave grooming", "sharp", false},
    {"🧴", "lotion bottle", "skincare moisturizer", "shampoo sunscreen", false},
    {"🧷", "safety pin", "fasten diaper", "punk rock", false},
    {"🛏️", "bed", "sleep rest bedroom", "hotel", false},
    {"🛋️", "couch lamp", "sofa furniture living room", "hotel", false},
    {"🪑", "chair", "furniture seat sit", "", false},
    {"🚪", "door", "entrance exit open", "back closet front", false},
    {"🪞", "mirror", "reflection glass", "makeup reflector speculum", false},
    {"🪟", "window", "glass open view", "air frame fresh opening transparent", false},
    {"🛍️", "shopping bags", "shop retail buy", "bag hotel", false},
    {"🎒", "backpack", "school bag travel", "backpacking bookbag education rucksack satchel", false},
    {"👝", "clutch bag", "purse fashion", "clothes clothing dress handbag pouch", false},
    {"👛", "purse", "wallet fashion money", "clothes clothing coin dress fancy handbag shopping", false},
    {"👜", "handbag", "purse fashion bag", "clothes clothing dress lady shopping", false},
    {"💼", "briefcase", "work business office", "", false},
    {"🧳", "luggage", "travel suitcase airport", "bag packing roller", false},
    {"☂️", "umbrella", "rain weather protect", "clothing", false},
    {"🌂", "closed umbrella", "rain weather", "clothing", false},
    {"🧵", "thread", "sewing needle craft", "spool string", false},
    {"🧶", "yarn", "knitting craft wool", "ball crochet knit", false},
    {"👓", "glasses", "eyewear vision read", "clothing eye eyeglasses", false},
    {"🕶️", "sunglasses", "cool shades summer", "dark eye eyewear glasses", false},
    {"🥽", "goggles", "swim lab safety", "dive eye protection scuba swimming welding", false},
    {"🥼", "lab coat", "science doctor white", "clothes dr experiment jacket scientist", false},
    {"🦺", "safety vest", "construction worker", "emergency", false},
    {"👔", "necktie", "formal business suit", "clothing employed serious shirt tie", false},
    {"👕", "t-shirt", "shirt clothes casual", "blue clothing collar dressed shopping tshirt weekend", false},
    {"👖", "jeans", "pants clothes denim", "blue casual clothing dressed shopping trousers weekend", false},
    {"🧣", "scarf", "winter warm clothes", "bundle cold neck up", false},
    {"🧤", "gloves", "winter hands warm", "hand", false},
    {"🧥", "coat", "jacket winter warm", "brr bundle cold up", false},
    {"🧦", "socks", "feet clothes warm", "stocking", false},
    {"👗", "dress", "clothes fashion woman", "clothing dressed fancy shopping", false},
    {"👘", "kimono", "japan clothes traditional", "clothing comfortable", false},
    {"🥻", "sari", "india clothes traditional", "clothing dress", false},
    {"🩱", "one piece swimsuit", "swim beach", "bathing one-piece suit", false},
    {"🩲", "briefs", "underwear clothes", "bathing one-piece suit swimsuit", false},
    {"🩳", "shorts", "clothes summer casual", "bathing pants suit swimsuit underwear", false},
    {"👙", "bikini", "swim beach summer", "bathing clothing pool suit", false},
    {"👚", "woman clothes", "blouse fashion", "clothing collar dress dressed lady shirt shopping woman’s", false},
    {"❤️", "red heart", "love like romance", "emotion <3", false},
    {"🧡", "orange heart", "love", "143", false},
    {"💛", "yellow heart", "love friendship", "143 cardiac emotion ily", false},
    {"💚", "green heart", "love nature", "143 emotion ily romantic", false},
    {"💙", "blue heart", "love trust", "143 emotion ily romance", false},
    {"💜", "purple heart", "love", "143 bestest emotion ily", false},
    {"🖤", "black heart", "dark love goth", "evil wicked", false},
    {"🤍", "white heart", "pure love", "143", false},
    {"🤎", "brown heart", "love earth", "143", false},
    {"💔", "broken heart", "sad breakup hurt", "break crushed emotion heartbroken lonely dumped", false},
    {"❣️", "heart exclamation", "love emphasis", "heavy punctuation", false},
    {"💕", "two hearts", "love romance", "143 anniversary date dating emotion heart ily kisses loving xoxo", false},
    {"💞", "revolving hearts", "love romance", "143 adorbs anniversary emotion heart", false},
    {"💓", "beating heart", "love pulse", "143 cardio emotion heartbeat ily pulsating", false},
    {"💗", "growing heart", "love excited", "143 emotion heartpulse ily kisses muah nervous pulse xoxo", false},
    {"💖", "sparkling heart", "love shine", "143 emotion excited good ily kisses morning night sparkle xoxo", false},
    {"💘", "heart arrow", "cupid love valentine", "143 adorbs date emotion ily romance", false},
    {"💝", "heart ribbon", "gift valentine love", "143 anniversary emotion ily kisses xoxo", false},
    {"💟", "heart decoration", "love purple", "143 emotion hearth white", false},
    {"☮️", "peace symbol", "hippie harmony", "healing peaceful", false},
    {"✝️", "latin cross", "christian religion", "christ", false},
    {"☪️", "star crescent", "islam religion", "muslim ramadan", false},
    {"🕉️", "om", "hindu religion", "", false},
    {"☸️", "wheel of dharma", "buddhist religion", "", false},
    {"✡️", "star of david", "jewish religion", "jew judaism", false},
    {"🔯", "dotted six pointed star", "fortune", "jewish judaism six-pointed", false},
    {"🕎", "menorah", "hanukkah jewish", "candelabrum candlestick judaism religion", false},
    {"☯️", "yin yang", "balance tao", "difficult lives religion taoist total yinyang", false},
    {"🆗", "ok button", "yes approve", "okay", false},
    {"🆒", "cool button", "awesome", "", false},
    {"🆕", "new button", "fresh latest", "", false},
    {"🆙", "up button", "level increase", "up!", false},
    {"🆓", "free button", "gratis no cost", "", false},
    {"0️⃣", "keycap zero", "number 0", "keycap:", false},
    {"1️⃣", "keycap one", "number 1", "keycap:", false},
    {"2️⃣", "keycap two", "number 2", "keycap:", false},
    {"3️⃣", "keycap three", "number 3", "keycap:", false},
    {"4️⃣", "keycap four", "number 4", "keycap:", false},
    {"5️⃣", "keycap five", "number 5", "keycap:", false},
    {"6️⃣", "keycap six", "number 6", "keycap:", false},
    {"7️⃣", "keycap seven", "number 7", "keycap:", false},
    {"8️⃣", "keycap eight", "number 8", "keycap:", false},
    {"9️⃣", "keycap nine", "number 9", "keycap:", false},
    {"🔟", "keycap ten", "number 10", "", false},
    {"🔢", "input numbers", "123 digits", "1234", false},
    {"▶️", "play button", "start video music", "arrow right triangle", false},
    {"⏸️", "pause button", "stop wait", "bar double vertical", false},
    {"⏹️", "stop button", "end halt", "square", false},
    {"⏺️", "record button", "capture red dot", "circle", false},
    {"⏭️", "next track", "skip forward", "arrow scene triangle", false},
    {"⏮️", "last track", "skip back", "arrow previous scene triangle", false},
    {"⏩", "fast forward", "speed skip", "arrow double fast-forward", false},
    {"⏪", "fast reverse", "rewind back", "arrow double", false},
    {"🔀", "shuffle tracks", "random music", "arrow crossed", false},
    {"🔁", "repeat button", "loop again", "arrow clockwise", false},
    {"🔂", "repeat single", "loop one song", "arrow clockwise once", false},
    {"⬆️", "up arrow", "direction north", "cardinal", false},
    {"↗️", "up right arrow", "direction", "intercardinal northeast up-right", false},
    {"➡️", "right arrow", "direction east", "cardinal", false},
    {"↘️", "down right arrow", "direction", "down-right intercardinal southeast", false},
    {"⬇️", "down arrow", "direction south", "cardinal", false},
    {"↙️", "down left arrow", "direction", "down-left intercardinal southwest", false},
    {"⬅️", "left arrow", "direction west", "cardinal", false},
    {"↖️", "up left arrow", "direction", "intercardinal northwest up-left", false},
    {"↕️", "up down arrow", "vertical sort", "up-down", false},
    {"↔️", "left right arrow", "horizontal swap", "left-right", false},
    {"🔄", "counterclockwise arrows", "refresh reload sync", "again anticlockwise arrow deja rewindershins vu", false},
    {"🔃", "clockwise arrows", "reload refresh", "arrow vertical", false},
    {"➕", "plus", "add math positive", "", false},
    {"➖", "minus", "subtract math negative", "heavy", false},
    {"✖️", "multiply", "times math x", "cancel multiplication", false},
    {"➗", "divide", "math division", "heavy", false},
    {"♾️", "infinity", "forever endless", "unbounded universal", false},
    {"‼️", "double exclamation", "emphasis alert", "!! bangbang punctuation", false},
    {"⁉️", "exclamation question", "surprise confused", "!? interrobang punctuation", false},
    {"❓", "question mark", "help what ask", "punctuation red", false},
    {"❔", "white question", "help ask", "outlined punctuation", false},
    {"❕", "white exclamation", "alert notice", "outlined punctuation", false},
    {"❗", "exclamation mark", "alert important warning", "punctuation red", false},
    {"〰️", "wavy dash", "line squiggle", "punctuation", false},
    {"💱", "currency exchange", "money convert forex", "bank", false},
    {"💲", "heavy dollar sign", "money price cost", "billion cash charge currency million pay", false},
    {"⚕️", "medical symbol", "health doctor", "aesculapius medicine staff", false},
    {"♻️", "recycling symbol", "green eco recycle", "", false},
    {"🔱", "trident emblem", "poseidon anchor", "ship tool", false},
    {"📛", "name badge", "id label tag", "", false},
    {"🔰", "japanese symbol beginner", "new learner", "chevron green leaf tool yellow", false},
    {"⭕", "hollow red circle", "o mark", "heavy large", false},
    {"✅", "check mark button", "done yes correct", "checked checkmark complete completed fixed tick", false},
    {"☑️", "check box with check", "done task complete", "ballot checked off tick", false},
    {"✔️", "check mark", "done correct yes", "checked checkmark heavy tick", false},
    {"❌", "cross mark", "no wrong delete cancel", "multiplication multiply", false},
    {"❎", "cross mark button", "no cancel close", "multiplication multiply square", false},
    {"➰", "curly loop", "swirl decoration", "curl", false},
    {"➿", "double curly loop", "phone fax", "curl", false},
    {"〽️", "part alternation mark", "japanese music", "", false},
    {"✳️", "eight spoked asterisk", "star sparkle", "eight-spoked", false},
    {"✴️", "eight pointed star", "orange star", "eight-pointed", false},
    {"❇️", "sparkle", "shine glitter", "", false},
    {"©️", "copyright", "legal rights", "", false},
    {"®️", "registered", "trademark legal", "", false},
    {"™️", "trade mark", "brand legal", "tm trademark", false},
    {"🔴", "red circle", "dot color", "geometric", false},
    {"🟠", "orange circle", "dot color", "", false},
    {"🟡", "yellow circle", "dot color", "", false},
    {"🟢", "green circle", "dot color", "", false},
    {"🔵", "blue circle", "dot color", "geometric", false},
    {"🟣", "purple circle", "dot color", "", false},
    {"🟤", "brown circle", "dot color", "", false},
    {"⚫", "black circle", "dot dark", "geometric", false},
    {"⚪", "white circle", "dot light", "geometric", false},
    {"🟥", "red square", "color block", "card penalty", false},
    {"🟧", "orange square", "color block", "", false},
    {"🟨", "yellow square", "color block", "card penalty", false},
    {"🟩", "green square", "color block", "", false},
    {"🟦", "blue square", "color block", "", false},
    {"🟪", "purple square", "color block", "", false},
    {"🟫", "brown square", "color block", "", false},
    {"⬛", "black large square", "dark block", "geometric", false},
    {"⬜", "white large square", "light block", "geometric", false},
    {"🔶", "large orange diamond", "shape color", "geometric", false},
    {"🔷", "large blue diamond", "shape color", "geometric", false},
    {"🔸", "small orange diamond", "shape color", "geometric", false},
    {"🔹", "small blue diamond", "shape color", "geometric", false},
    {"🔺", "red triangle pointed up", "arrow shape", "geometric", false},
    {"🔻", "red triangle pointed down", "arrow shape", "geometric", false},
    {"💠", "diamond with dot", "cute shape", "comic geometric", false},
    {"🔘", "radio button", "select option", "geometric", false},
    {"🔳", "white square button", "ui button", "geometric outlined", false},
    {"🔲", "black square button", "ui button", "geometric", false},
    {"🏁", "chequered flag", "race finish win", "checkered flags game racing sport", false},
    {"🚩", "triangular flag", "red flag mark", "construction golf post", false},
    {"🎌", "crossed flags", "japan celebration", "cross japanese", false},
    {"🏴", "black flag", "pirate waving", "", false},
    {"🏳️", "white flag", "surrender peace", "waving", false},
    {"🏳️‍🌈", "rainbow flag", "pride lgbt", "bisexual gay genderqueer glbt glbtq lesbian lgbtq lgbtqia queer trans transgender", false},
    {"🏳️‍⚧️", "transgender flag", "pride trans", "blue light pink white", false},
    {"🏴‍☠️", "pirate flag", "skull crossbones", "jolly plunder roger treasure", false},
    {"🇺🇸", "flag united states", "america usa", "us", false},
    {"🇬🇧", "flag united kingdom", "britain uk england", "british", false},
    {"🇫🇷", "flag france", "french", "", false},
    {"🇩🇪", "flag germany", "german", "deutschland", false},
    {"🇯🇵", "flag japan", "japanese", "nippon", false},
    {"🇰🇷", "flag south korea", "korean", "", false},
    {"🇨🇳", "flag china", "chinese", "prc", false},
    {"🇮🇳", "flag india", "indian", "bharat", false},
    {"🇧🇷", "flag brazil", "brazilian", "brasil", false},
    {"🇨🇦", "flag canada", "canadian", "", false},
    {"🇦🇺", "flag australia", "australian", "aus", false},
    {"🇮🇹", "flag italy", "italian", "italia", false},
    {"🇪🇸", "flag spain", "spanish", "espana", false},
    {"🇷🇺", "flag russia", "russian", "", false},
    {"🇲🇽", "flag mexico", "mexican", "", false},
    {"🔥", "fire", "hot flame lit trending", "af burn litaf tool", false},
    {"✨", "sparkles", "shine magic glitter stars", "sparkle star", false},
    {"⭐", "star", "favorite rating gold", "astronomy medium stars white", false},
    {"🌟", "glowing star", "shine sparkle amazing", "glittery glow night shining win", false},
    {"💫", "dizzy", "star sparkle shooting", "comic shining stars", false},
    {"⚡", "high voltage", "lightning fast electric zap", "danger electricity nature thunder thunderbolt", false},
    {"☀️", "sun", "sunny bright day weather", "rays space", false},
    {"🌤️", "sun behind small cloud", "partly cloudy weather", "", false},
    {"⛅", "sun behind cloud", "cloudy weather", "", false},
    {"🌥️", "sun behind large cloud", "overcast weather", "", false},
    {"☁️", "cloud", "weather sky grey", "", false},
    {"🌦️", "sun behind rain cloud", "weather rain sun", "", false},
    {"🌧️", "cloud with rain", "rainy weather wet", "", false},
    {"⛈️", "cloud lightning", "storm thunder weather", "rain thunderstorm", false},
    {"🌩️", "cloud with lightning", "storm electric weather", "", false},
    {"🌨️", "cloud with snow", "snow winter weather", "cold", false},
    {"❄️", "snowflake", "winter cold freeze", "snow weather", false},
    {"☃️", "snowman", "winter christmas cold", "man snow", false},
    {"⛄", "snowman without snow", "winter cold", "man", false},
    {"🌬️", "wind face", "blow gust weather", "cloud", false},
    {"💨", "dashing away", "wind fast speed run", "cloud comic dash fart go gone gotta running smoke", false},
    {"🌪️", "tornado", "storm cyclone weather", "cloud whirlwind", false},
    {"🌫️", "fog", "mist weather haze", "cloud", false},
    {"🌈", "rainbow", "pride colorful weather", "gay genderqueer glbt glbtq lesbian lgbt lgbtq lgbtqia nature queer rain trans transgender", false},
    {"☔", "umbrella with rain", "wet weather rainy", "clothing drop drops", false},
    {"🌊", "water wave", "ocean surf beach", "nature surfer surfing", false},
    {"🍀", "four leaf clover", "luck irish green", "four-leaf lucky plant", false},
    {"🌸", "cherry blossom", "spring flower japan", "plant springtime", false},
    {"💐", "bouquet", "flowers gift romance", "anniversary birthday date flower love plant", false},
    {"🌹", "rose", "flower love romance red", "beauty elegant plant valentine", false},
    {"🥀", "wilted flower", "sad dead rose", "dying", false},
    {"🌺", "hibiscus", "flower tropical hawaii", "plant", false},
    {"🌻", "sunflower", "flower yellow summer", "outdoors plant sun", false},
    {"🌼", "blossom", "flower spring daisy", "buttercup dandelion plant", false},
    {"🌷", "tulip", "flower spring netherlands", "blossom growth plant", false},
    {"🌱", "seedling", "plant grow sprout green", "sapling young", false},
    {"🪴", "potted plant", "houseplant grow green", "decor house nurturing pot", false},
    {"🌲", "evergreen tree", "pine forest christmas", "", false},
    {"🌳", "deciduous tree", "nature forest park", "green habitat shedding", false},
    {"🌴", "palm tree", "tropical beach vacation", "plant", false},
    {"🌵", "cactus", "desert plant dry", "drought nature", false},
    {"🌾", "sheaf of rice", "grain harvest farm", "ear grains plant", false},
    {"🌿", "herb", "leaf plant green nature", "", false},
    {"☘️", "shamrock", "irish luck clover", "plant", false},
    {"🍁", "maple leaf", "canada autumn fall", "falling", false},
    {"🍂", "fallen leaf", "autumn fall season", "falling", false},
    {"🍃", "leaf fluttering wind", "nature breeze green", "blow flutter", false},
};

inline constexpr int kEmojiCount = 728;
